### ISSUE TITLE
Freezes with FPC 3.2

### ISSUE THREAD

**Issue by GitStorageOne** [mr-highball/ezthreads#5] opened 2020-04-24 21:59 UTC
Testing `ezthreads_tester_ui` with lazarus 2.0.9 and fpc 3.2.
After pressing `Do it` button main thread freezes after 10 sec.

---

Is there a way to set thread name?

**Comment by mr-highball** [comment] 2020-04-24 22:54
@GitStorageOne 
confirmed the freeze (haven't looked at the ui tester in a while). I'll update the test so it's correct (or fix an issue with synchronize if there is one).
Also, you mean the thread name in the debugger correct? If so I've been meaning to do that, just haven't added it yet, I'll push that along with a commit for your issue

**Comment by mr-highball** [comment] 2020-04-25 00:57
@GitStorageOne just committed two changes to ezthreads
* a626cfe should fix the locking issue
* 64775fb added a name property `ezthreads.settings.name` which will be used for debugging

after doing some research, the problem is that the mechanism for naming threads isn't implemented in fpc yet (see: https://forum.lazarus.freepascal.org/index.php?topic=32745.60). Once they settle on an approach, the code will be in place to show in the debugger, but until then inspecting in the evaluate/modify or inspection window should be able to show the thread name you set.

Let me know if this addresses the problem for you, and feel free to close the issue if it does, otherwise I'll mark this one as fixed

**Comment by mr-highball** [comment] 2020-04-25 00:59
also noting that there is a fluent method for updating the thread name as well implemented in 
a7f60c0

`ezthread.Settings.UpdateThreadName('yourName')`

**Closed** 2020-04-25 07:33 UTC
